# install Docker CE
- name: install required packages
  become: yes
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
    update_cache: yes
    state: latest

- name: add Docker's official GPG key
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: False

- name: get ubuntu name
  shell: echo $(lsb_release -cs)
  register: distribution

- name: add Docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution.stdout }} stable

- name: install Docker
  become: yes
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    update_cache: yes

- name: create a Docker group
  group:
    name: docker
    state: present

- name: add user to Docker group
  become: yes
  user:
    name: "{{ user }}"
    groups: docker
    append: yes