# install general packages
- name: install packages
  become: yes
  apt:
    name: ["git", "curl", "build-essential", "cmake", "dconf-tools"]
    update_cache: yes
    state: latest

- name: update all remaining packages
  become: yes
  apt:
    upgrade: dist

- name: remap caps lock 
  command: dconf write /org/gnome/desktop/input-sources/xkb-options "['ctrl:nocaps']"

