# set up automatic backups
- name: create necessary directories
  file:
    path: /home/{{ deploy_user }}/{{ item }}
    state: directory
  with_items: 
    - backups
    - scripts
    - logs

- name: write backup script
  template:
    src: auto_backup.j2
    dest: /home/{{ deploy_user }}/scripts/{{ app_name }}_backup.sh

# create a cron job
- name: setup a cron job to run the backup script
  cron:
    name: "{{ app_name }} backup"
    minute: 00
    hour: 01
    job: "~/scripts/{{ app_name }}_backup.sh >> ~/logs/{{ app_name }}-backup.log"
