# update all packages
- name: update all packages
  apt:
    update_cache: yes
    upgrade: yes
  become: yes

# https://stackoverflow.com/questions/23877781/how-to-wait-for-server-restart-using-ansible
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: reboot system if needed
  shell: sleep 1 && reboot "system restarting" && sleep 1
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  when: reboot_required_file.stat.exists

- name: Waiting for the machine to come back
  local_action: 
    module: wait_for 
      host={{ ansible_ssh_host }} 
      state=started 
      port=22 
      delay=30
  become: no
  when: reboot_required_file.stat.exists
