# nginx configuration
- name: ensure Ngninx is installed
  apt: name=nginx state=present update_cache=yes
  become: yes

- name: ensure Lets Encrypt is installed
  apt: name=letsencrypt state=present update_cache=yes
  become: yes

- name: write Ngnix configuration
  template: src=nginx_conf.j2
            dest=/etc/nginx/conf.d/{{ app_name }}.conf
  become: yes

- name: create Lets Encrypt directory
  file: name=/var/www/letsencrypt state=directory
  become: yes

- name: remove default Nginx configuration
  file: name=/etc/ngninx/sites-enabled/default state=absent
  become: yes

- name: check if certificate already created
  stat: 
    path: "/etc/letsencrypt/live/{{ fqdn }}"
  register: certs
  become: yes

- name: stop Nginx to get cert
  service: 
    name: nginx
    state: stopped
  become: yes
  when: not certs.stat.exists

- name: create Lets Encrypt certificate
  shell: "letsencrypt certonly --standalone -d {{ fqdn }} -w {{ web_serve_dir }} -m {{ ssl_cert_email }} --agree-tos --renew-by-default --non-interactive"
  become: yes
  when: not certs.stat.exists

- name: generate Diffie-Hellman group 
  shell: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
  become: yes
  when: not certs.stat.exists

- name: start Nginx after getting cert
  service: 
    name: nginx
    state: started
  become: yes

